name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: get-cmake
      uses: lukka/get-cmake@v3.22.2
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    
    - name: "Create build directory and run CMake"
      working-directory: ${{github.workspace}}/Team09/Code09
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        
    - name: "Build Project" 
      working-directory: ${{github.workspace}}/Team09/Code09
      run: cmake --build build --target all --config Release -- -j4 

    - name: once CMake has done its job we just build using make as usual
      working-directory: ${{github.workspace}}/Team09/Code09/build
      shell: bash
      run: make -j4
      
    - name: run unit test
      working-directory: ${{github.workspace}}/Team09/Code09/build
      shell: bash
      run: ../src/unit_testing/unit_testing
      
    - name: run integration test
      working-directory: ${{github.workspace}}/Team09/Code09/build
      shell: bash
      run: ../src/integration_testing/integration_testing
