name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: get-cmake
      uses: lukka/get-cmake@v3.22.2
      
    - name: Installing HomeBrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      
    - name: Installing CMake
      run: brew install cmake llvm
    
    - name: mkdir build
      working-directory: ${{github.workspace}}/Team09/Code09
      run: mkdir build
        
    - name: "Build Project" 
      working-directory: ${{github.workspace}}/Team09/Code09/build
      run: cmake ..

    - name: once CMake has done its job we just build using make as usual
      working-directory: ${{github.workspace}}/Team09/Code09/build
      shell: bash
      run: make -j4
      
    - name: run unit test
      working-directory: ${{github.workspace}}/Team09/Code09/build
      shell: bash
      run: ./src/unit_testing/unit_testing
      
    - name: run integration test
      working-directory: ${{github.workspace}}/Team09/Code09/build
      shell: bash
      run: ./src/integration_testing/integration_testing
